myfileapp/urls.py
from django.urls import path
from . import views


app_name = "fileapp"


urlpatterns = [
    path("",views.index,name="home"),
    path("home2",views.index1,name="home2"),
    path("upload",views.send_files,name="uploads"),
]

myproj/urls.py
from django.contrib import admin
from django.urls import path,include


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("myfileapp.urls",namespace="fileapp"))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myfileapp/models.py
from django.db import models

# Create your models here.


class myuploadfile(models.Model):
    f_name = models.CharField(max_length=255)
    myfiles = models.FileField(upload_to="")

    def __str__(self):
        return self.f_name

myfileapp/views.py
from django.shortcuts import render,HttpResponse,redirect
from .models import myuploadfile
import cv2
import numpy as np
import pytesseract
import os
import PyPDF2
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Create your views here.
def index(request):
    return render(request,"index.html")

def index1(request):
    context = {
        "data":myuploadfile.objects.all(),
    }
    return render(request,"index1.html",context)

global s_vectors

def text_plagiarism():
    path = "C:\myproj\myfileapp"
    os.chdir(path)
    pdftotext()
    imgtotext()
    student_files = [doc for doc in os.listdir() if doc.endswith('.txt')]
    student_notes = [open(File).read() for File in student_files]


    vectorize = lambda Text: TfidfVectorizer().fit_transform(Text).toarray()
    similarity = lambda doc1, doc2: cosine_similarity([doc1, doc2])

    vectors = vectorize(student_notes)
    s_vectors = list(zip(student_files, vectors))
    plagiarism_results = set()

    for student_a, text_vector_a in s_vectors:
        new_vectors = s_vectors.copy()
        current_index = new_vectors.index((student_a, text_vector_a))
        del new_vectors[current_index]
        for student_b, text_vector_b in new_vectors:
            sim_score = similarity(text_vector_a, text_vector_b)[0][1]
            sim_score_per = sim_score*100
            sim_score_dec = "{:.2f}".format(sim_score_per) + "%"
            student_pair = sorted((student_a, student_b))
            score = (student_pair[0], student_pair[1], sim_score_dec)
            plagiarism_results.add(score)
    
    for i in student_files:
        os.remove(i)
    return plagiarism_results
    


def pdftotext():
    doc_name = [doc for doc in os.listdir() if doc.endswith('.pdf')]

    for name in doc_name:
        pdfFileObj = open(name,'rb')
        pdfreader = PyPDF2.PdfFileReader(pdfFileObj)
        no_of_pages = pdfreader.numPages
                
                
        name1 = name.split('.')
        res1=name1[0]
        res1 = res1 + ".txt"
        f = open(res1,"w+")
        string = ""
        for i in range(0,no_of_pages):
            pageObj = pdfreader.getPage(i)
            string = string + pageObj.extractText()
            #print(pageObj.extractText())
            f.write(string)   
        pdfFileObj.close()
        os.remove(name) 
       
        
def imgtotext():
    pytesseract.pytesseract.tesseract_cmd = r"C:\Program Files\Tesseract-OCR\tesseract.exe"

    img_name = [doc for doc in os.listdir() if doc.endswith('.png')]

    for name in img_name:
        img = cv2.imread(name)
        imp = cv2.resize(img, None, fx=0.5, fy=0.5)
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

        adaptive_threshold = cv2.adaptiveThreshold(gray, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 85, 11)

        config = "--psm 4"
        text = pytesseract.image_to_string(adaptive_threshold, config=config)

        name1 = name.split('.')
        res1=name1[0]
        res1 = res1 + ".txt"
        f = open(res1,"w+")

        outfile = open(res1, 'a+',encoding='utf-8')
        outfile.write(text)
        outfile.close()
        newfile = open(res1, 'r',encoding='utf-8')
        os.remove(name)        


def send_files(request):
    if request.method == "POST" :
        name = request.POST.get("filename")
        myfile = request.FILES.getlist("uploadfoles")
        
        for f in myfile:
            myuploadfile(f_name=name,myfiles=f).save()
        


        all_mix = list(text_plagiarism())
        percents=[]
        docs, doc = [],[]
        for n in range(len(all_mix)):
            percents.append(all_mix[n][2])
            doc.append(all_mix[n][:2])
        
        for elements in doc:
            str = ' & '.join(elements)
            docs.append(str)
        
        context1={
            "data1" : docs,
            "data2" : percents,
            
        }
              
        return render(request,"final.html",context1)
        



        

templates/final.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <style>
        a.ex2:hover, a.ex2:active {font-size: 150%;}
    </style>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,600,700,800,900" rel="stylesheet">

    <title>Documents Plagiarism Checker</title>
    
    <!-- Bootstrap core CSS -->
    <link href="{%  static  'vendor/bootstrap/css/bootstrap.min.css'  %}" rel="stylesheet">
    
    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{%  static  'assets/css/fontawesome.css'  %}">
    <link rel="stylesheet" href="{%  static  'assets/css/templatemo-grad-school.css'  %}">
    <link rel="stylesheet" href="{%  static  'assets /css/owl.css'  %}">
    <link rel="stylesheet" href="{%  static  'assets/css/lightbox.css'  %}">
<!--
    
TemplateMo 557 Grad School

https://templatemo.com/tm-557-grad-school

-->
  </head>

<body>

   
  <!--header-->
  <header class="main-header clearfix" role="header">
    <div class="logo">
      <a href="{% url 'fileapp:home' %}"><em>Plagiarism</em> Detector</a>
    </div>
    <a href="#menu" class="menu-link"><i class="fa fa-bars"></i></a>
    <nav id="menu" class="main-nav" role="navigation">
      <ul class="main-menu">
        <li><a href="#section1">Upload Documents</a></li> 
        <li class="has-submenu"><a href="#section2">How to use it?</a>
        </li>
        <li><a href="https://combinepdf.com">Change document format</a></li>
        <!-- <li><a href="#section5">Video</a></li> -->
      </ul>
    </nav>
  </header>


    <!-- ***** Main Banner Area Start ***** -->
      <video autoplay muted loop id="bg-video">
          <source src="{%  static  'assets/images/course-video.mp4'  %}" type="video/mp4" />
      </video>

      <div class="video-overlay header-text">
            <div class="caption">
                <div style = "position:relative; padding:190px 300px; ">
                    
                    
                        <div class="container" style="overflow: hidden;">
                            <div class="floatLeft" style="width: 50%; float: left;">
                                <table class="table table-striped table-dark" style="color:white; float: left;">
                                <thead class="thead-dark">
                                <tr>
                                <th style="text-align:center" scope="col">Compared Files</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for d1 in data1 %}
                                <tr>
                                <td>{{ d1 }}</td>
                                </tr>

                                {% endfor %}
                                </tbody>
                                </table>
                            </div>

                            <div class="floatRight" style="width: 50%; float: right;">
                                <table class="table table-striped table-dark" style="color:white; float: right;">
                                <thead class="thead-dark">
                                <tr>
                                <th style="text-align:center" scope="col">Plagiarism</th>
                                </tr>
                                </thead>

                                <tbody style="text-align:center">
                                {% for d2 in data2 %}
                                <tr>
                                <td>{{ d2 }}</td>
                                </tr>
                                {% endfor %}
                                </tbody>
                                </table>
                            </div>
                        </div>
                        <a href="{% url 'fileapp:home' %}"><button type="button" style="margin-left:auto;margin-right:auto;display:block;margin-top:7%;" class="btn btn-outline-primary"><strong>Check More</strong></button></a>
            
                </div>
              </div>
      </div>

      
  <!-- ***** Main Banner Area End ***** -->
    
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <p><i class="fa fa-copyright"></i> Copyright 2020 by Plagiarism Detector
        </div>
      </div>
    </div>
  </footer>    

</body>
</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,600,700,800,900" rel="stylesheet">

    <title>Documents Plagiarism Detector</title>
    
    <!-- Bootstrap core CSS -->
    <link href="{%  static  'vendor/bootstrap/css/bootstrap.min.css'  %}" rel="stylesheet">
    
    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{%  static  'assets/css/fontawesome.css'  %}">
    <link rel="stylesheet" href="{%  static  'assets/css/templatemo-grad-school.css'  %}">
    <link rel="stylesheet" href="{%  static  'assets /css/owl.css'  %}">
    <link rel="stylesheet" href="{%  static  'assets/css/lightbox.css'  %}">
<!--
    
TemplateMo 557 Grad School

https://templatemo.com/tm-557-grad-school

-->
  </head>

<body>

   
  <!--header-->
  <header class="main-header clearfix" role="header">
    <div class="logo">
      <a href="#"><em>Plagiarism</em> Detector</a>
    </div>
    <a href="#menu" class="menu-link"><i class="fa fa-bars"></i></a>
    <nav id="menu" class="main-nav" role="navigation">
      <ul class="main-menu">
        <li><a href="#section1">Upload Documents</a></li> 
        <li class="has-submenu"><a href="#section2">How to use it?</a>
        </li>
        <li><a href="#section3">Change document format</a></li>
        <!-- <li><a href="#section5">Video</a></li> -->
      </ul>
    </nav>
  </header>

  <!-- ***** Main Banner Area Start ***** -->
  <section class="section main-banner" id="top" data-section="section1">
      <video autoplay muted loop id="bg-video">
          <source src="{%  static  'assets/images/course-video.mp4'  %}" type="video/mp4" />
      </video>

      <div class="video-overlay header-text">
          <div class="caption">
              <h6>Check the originality between documents using Plagiarism Detector</h6>
              <h2>Document <em>Plagiarism</em> Checker</h2>
              <div class="main-button">
                  <div class="scroll-to-section"><a href="#section2">Check for Plagiarism</a></div>
              </div>
          </div>
      </div>
  </section>
  <!-- ***** Main Banner Area End ***** -->


  <section class="features">
    <div class="container">
      <div class="row">
        <div class="col-lg-4 col-12">
          <div class="features-post">
            <div class="features-content">
              <div class="content-show">
                <h4><i class="fa fa-pencil"></i>Upload .txt files</h4>
              </div>
              <div class="content-hide">
                <p>Upload the file of the .txt format to be scanned here.The file should not be more than xMB</p>
                <a href="{% url 'fileapp:home2' %}">Upload</a>
            </div>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-12">
          <div class="features-post second-features">
            <div class="features-content">
              <div class="content-show">
                <h4><i class="fa fa-book"></i>Upload JPG Images</h4>
              </div>
              <div class="content-hide">
                <p>Upload the images of the .jpg format to be scanned here.The images should not be more than xMB</p>
                <a href="{% url 'fileapp:home2' %}">Upload</a>
            </div>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-12">
          <div class="features-post third-features">
            <div class="features-content">
              <div class="content-show">
                <h4><i class="fa fa-book"></i>Upload PDF's</h4>
              </div>
              <div class="content-hide">
                <p>Upload the PDF of the .pdf format to be scanned here.The PDF should not be more than xMB</p>
                <a href="{% url 'fileapp:home2' %}">Upload</a>
            </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="section why-us" data-section="section2">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="section-heading">
            <h2>How to perform a plagiarism check?</h2>
          </div>
        </div>
        <div class="col-md-12">
          <div id='tabs'>
            <ul>
              <li><a href='#tabs-1'>Upload Documents</a></li>
              <li><a href='#tabs-2'>Check for Plagiarism</a></li>
              <li><a href='#tabs-3'>Conclusion</a></li>
            </ul>
            <section class='tabs-content'>
              <article id='tabs-1'>
                <div class="row">
                  <div class="col-md-6">
                    <img src="{%  static  'assets/images/scan_image2.webp'  %}" alt="">
                  </div>
                  <div class="col-md-6">
                    <h4>Upload Documents</h4>
                    <p id = "para_font">The plagiarism checker works for files of the .txt,pdf and jpg formats only. Upload these files in their respective sections before performing a plagiarism check. There is no specific limit to the no of files that can be uploaded.However do note that more the number of files more will be the execution time. Incase a document of the respective format isnt available, the user can change the format of the document from the <a href="https://combinepdf.com">Change Document Format</a> option from the Navbar</p>
                  </div>
                </div>
              </article>
              <article id='tabs-2'>
                <div class="row">
                  <div class="col-md-6">
                    <img src="{%  static  'assets/images/plagiarism_image.png'  %}" alt="">
                  </div>
                  <div class="col-md-6">
                    <h4>Check for Plagiarism</h4>
                    <p id = "para_font">The plagiarism checkr checks for plagiarism between the uploaded files using the cosine similarity technique. It will check for plagiarism between all the documents uploaded respectively (checking for plagiarism between any 2 documents at a time, making nC2 comparisons where n is the no of documents uploaded) </p> 
                  </div>
                </div>
              </article>
              <article id='tabs-3'>
                <div class="row">
                  <div class="col-md-6">
                    <img src="{%  static  'assets/images/conclusion_image2.png'  %}" alt="">
                  </div>
                  <div class="col-md-6">
                    <h4>Conclusion</h4>
                    <p id = "para_font">Once the plagiarism check is over nC2 percentage values will be returned with their respective documents that were considered during the plagiarism check </p>
                  </div>
                </div>
              </article>
            </section>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="section why-us" data-section="section3">
    <div class="section-heading">
      <h2><a href = "https://combinepdf.com">Tap Here to change the format of the document/compress a document</a></h2>
    </div>
  </section>


  
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <p><i class="fa fa-copyright"></i> Copyright 2020 by Plagiarism Detector
        </div>
      </div>
    </div>
  </footer>

  <!-- Scripts -->
  <!-- Bootstrap core JavaScript -->
    <script src="{%  static  'vendor/jquery/jquery.min.js'  %}"></script>
    <script src="{%  static  'vendor/bootstrap/js/bootstrap.bundle.min.js'  %}"></script>

    <script src="{%  static  'assets/js/isotope.min.js'  %}"></script>
    <script src="{%  static  'assets/js/owl-carousel.js'  %}"></script>
    <script src="{%  static  'assets/js/lightbox.js'  %}"></script>
    <script src="{%  static  'assets/js/tabs.js'  %}"></script>
    <script src="{%  static  'assets/js/video.js'  %}"></script>
    <script src="{%  static  'assets/js/slick-slider.js'  %}"></script>
    <script src="{%  static  'assets/js/custom.js'  %}"></script>
    <script>
        //according to loftblog tut
        $('.nav li:first').addClass('active');

        var showSection = function showSection(section, isAnimate) {
          var
          direction = section.replace(/#/, ''),
          reqSection = $('.section').filter('[data-section="' + direction + '"]'),
          reqSectionPos = reqSection.offset().top - 0;

          if (isAnimate) {
            $('body, html').animate({
              scrollTop: reqSectionPos },
            800);
          } else {
            $('body, html').scrollTop(reqSectionPos);
          }

        };

        var checkSection = function checkSection() {
          $('.section').each(function () {
            var
            $this = $(this),
            topEdge = $this.offset().top - 80,
            bottomEdge = topEdge + $this.height(),
            wScroll = $(window).scrollTop();
            if (topEdge < wScroll && bottomEdge > wScroll) {
              var
              currentId = $this.data('section'),
              reqLink = $('a').filter('[href*=\\#' + currentId + ']');
              reqLink.closest('li').addClass('active').
              siblings().removeClass('active');
            }
          });
        };

        $('.main-menu, .scroll-to-section').on('click', 'a', function (e) {
          if($(e.target).hasClass('external')) {
            return;
          }
          e.preventDefault();
          $('#menu').removeClass('active');
          showSection($(this).attr('href'), true);
        });

        $(window).scroll(function () {
          checkSection();
        });
    </script>
</body>
</html>

templates/index1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,600,700,800,900" rel="stylesheet">

    <title>Documents Plagiarism Checker</title>
    
    <!-- Bootstrap core CSS -->
    <link href="{%  static  'vendor/bootstrap/css/bootstrap.min.css'  %}" rel="stylesheet">
    
    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{%  static  'assets/css/fontawesome.css'  %}">
    <link rel="stylesheet" href="{%  static  'assets/css/templatemo-grad-school.css'  %}">
    <link rel="stylesheet" href="{%  static  'assets /css/owl.css'  %}">
    <link rel="stylesheet" href="{%  static  'assets/css/lightbox.css'  %}">
<!--
    
TemplateMo 557 Grad School

https://templatemo.com/tm-557-grad-school

-->
  </head>

<body>
    <!--header-->
  <header class="main-header clearfix" role="header">
    <div class="logo">
      <a href="{% url 'fileapp:home' %}"><em>Plagiarism</em> Detector</a>
    </div>
    <a href="#menu" class="menu-link"><i class="fa fa-bars"></i></a>
    <nav id="menu" class="main-nav" role="navigation">
      <ul class="main-menu">
        <li><a href="#section1">Upload Documents</a></li> 
        <li class="has-submenu"><a href="#section2">How to use it?</a>
        </li>
        <li><a href = "https://combinepdf.com">Change document format</a></li>
        <!-- <li><a href="#section5">Video</a></li> -->
      </ul>
    </nav>
  </header>

    


    <form action="{% url 'fileapp:uploads' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <video autoplay muted loop id="bg-video">
          <source src="{%  static  'assets/images/course-video.mp4'  %}" type="video/mp4" />
    </video>
        <div class="video-overlay header-text">
            <div class="caption">
                <div class="main-button">
                    <div style = "position:relative; padding:190px 300px; ">
                        <div class="container">
                         <div class="col-md-12">
                                <div class="input-group mb-3 input-group-lg">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="inputGroup-sizing-default" style="color:white; background-color:#24a0ed;"><strong><i class="fa fa-folder"></i>    FileName</strong></span>
                                    </div>
                                        <input type="text" name="filename" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default">
                                </div>
                                <div class="input-group">
                                    <div class="custom-file" >
                                        <input type="file" class="input-group-text"  multiple name="uploadfoles" id="inputGroup-sizing-default">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
            
                    <div style = "position:relative;  text-align: center; bottom:75px;">
                        <button type="submit" class="btn btn-primary" style="padding: 15px 125px; font-size: 30px;"><strong>File Upload       </strong><i class="fa fa-upload"></i></button>
                    </div>
                </div>
            </div>
        </div>
    </form> 
  

  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <p><i class="fa fa-copyright"></i> Copyright 2020 by Plagiarism Detector
        </div>
      </div>
    </div>
  </footer>
 <!-- Scripts -->
  <!-- Bootstrap core JavaScript -->
    <script src="{%  static  'vendor/jquery/jquery.min.js'  %}"></script>
    <script src="{%  static  'vendor/bootstrap/js/bootstrap.bundle.min.js'  %}"></script>

    <script src="{%  static  'assets/js/isotope.min.js'  %}"></script>
    <script src="{%  static  'assets/js/owl-carousel.js'  %}"></script>
    <script src="{%  static  'assets/js/lightbox.js'  %}"></script>
    <script src="{%  static  'assets/js/tabs.js'  %}"></script>
    <script src="{%  static  'assets/js/video.js'  %}"></script>
    <script src="{%  static  'assets/js/slick-slider.js'  %}"></script>
    <script src="{%  static  'assets/js/custom.js'  %}"></script>
    <script>
        //according to loftblog tut
        $('.nav li:first').addClass('active');

        var showSection = function showSection(section, isAnimate) {
          var
          direction = section.replace(/#/, ''),
          reqSection = $('.section').filter('[data-section="' + direction + '"]'),
          reqSectionPos = reqSection.offset().top - 0;

          if (isAnimate) {
            $('body, html').animate({
              scrollTop: reqSectionPos },
            800);
          } else {
            $('body, html').scrollTop(reqSectionPos);
          }

        };

        var checkSection = function checkSection() {
          $('.section').each(function () {
            var
            $this = $(this),
            topEdge = $this.offset().top - 80,
            bottomEdge = topEdge + $this.height(),
            wScroll = $(window).scrollTop();
            if (topEdge < wScroll && bottomEdge > wScroll) {
              var
              currentId = $this.data('section'),
              reqLink = $('a').filter('[href*=\\#' + currentId + ']');
              reqLink.closest('li').addClass('active').
              siblings().removeClass('active');
            }
          });
        };

        $('.main-menu, .scroll-to-section').on('click', 'a', function (e) {
          if($(e.target).hasClass('external')) {
            return;
          }
          e.preventDefault();
          $('#menu').removeClass('active');
          showSection($(this).attr('href'), true);
        });

        $(window).scroll(function () {
          checkSection();
        });
    </script>

</body>
</html>